### ISSUE TITLE
Fix checkstyle issues in test files.

### ISSUE THREAD

**Issue by conniey** [Azure/qpid-proton-j-extensions#39]
Enable `<includeTestSourceDirectory>true</includeTestSourceDirectory>` in pom.xml when checkstyle failures for tests have been fixed.

**Comment by SivaTharun** [comment]
@conniey can i work on this issue, i would like to contribute to Azure project.

**Comment by conniey** [comment]
@SivaTharun That would be awesome! Thanks! :D

**Comment by SivaTharun** [comment]
@conniey i have addressed the checkstyle issues from src/test package, please review this [PR](https://github.com/Azure/qpid-proton-j-extensions/pull/47).

**Comment by SivaTharun** [comment]
@conniey i have addressed your review comments on the above mentioned PR, please check it.
